// src/ui/src/views/main/Main.tsx
export function Main() {
  return (
    <main>
      <div className="main-container">
        <div className="title-container">
          <h1>title</h1>
        </div>

        <div className="input-wrapper">
          <input />
        </div>

        <div className="recently-visited">
          <div>Notion</div>
          <div>Figma</div>
        </div>
      </div>
    </main>
  );
}

// src/ui/src/views/main/Main.svelte
<script lang="ts">
</script>

<main>
  <div class="main-container">
    <div class="title-container">
      <h1>title</h1>
    </div>

    <div class="input-wrapper">
      <input />
    </div>

    <div class="recently-visited">
      <div>Notion</div>
      <div>Figma</div>
    </div>
  </div>
</main>

<style type="scss">
</style>
